name: Apptainer Convert Deploy

on:
  pull_request:
  push:
    branches: main

jobs:
  build-test-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    name: Build Container
    steps:
      - name: Check out code for the container builds
        uses: actions/checkout@v4

      - name: Setup Apptainer
        uses: eWaterCycle/setup-apptainer@v2
        with:
          apptainer-version: 1.3.2

      - name: Convert Container
        id: convert-container
        uses: andstor/docker2apptainer@main
        with:
          docker-image: ghcr.io/huggingface/text-generation-inference:2.4.0
          save-path: text-generation-inference.sif
      
      - name: Login and Deploy Container
        run: |
           echo ${{ secrets.GITHUB_TOKEN }} | singularity registry login -u ${{ secrets.GHCR_USERNAME }} --password-stdin oras://ghcr.io
           singularity push ${steps.convert-container.outputs.save-path} oras://ghcr.io/${GITHUB_REPOSITORY}:${tag}
